package com.projet.air2.entities;

// Generated 1 févr. 2017 02:18:12 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Administrateur generated by hbm2java
 */
@Entity
@Table(name = "administrateur", catalog = "projetair")
public class Administrateur implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long idadmin;
	private Role role;
	private String username;
	private String password;
	private Boolean active;
	private String nom;
	private String prenom;
	private String datenaissance;
	private String telephone;
	private String adresse;
	private String nomphoto;
	private byte[] photo;
	private Set<Ecole> ecoles = new HashSet<Ecole>(0);
	private Set<Gerant> gerants = new HashSet<Gerant>(0);

	public Administrateur() {
	}

	public Administrateur(Role role) {
		this.role = role;
	}

	public Administrateur(Role role, String username, String password,
			Boolean active, String nom, String prenom, String datenaissance,
			String telephone, String adresse, String nomphoto, byte[] photo,
			Set<Ecole> ecoles, Set<Gerant> gerants) {
		this.role = role;
		this.username = username;
		this.password = password;
		this.active = active;
		this.nom = nom;
		this.prenom = prenom;
		this.datenaissance = datenaissance;
		this.telephone = telephone;
		this.adresse = adresse;
		this.nomphoto = nomphoto;
		this.photo = photo;
		this.ecoles = ecoles;
		this.gerants = gerants;
	}

	public Administrateur(String username, String password, Boolean active,
			String nom, String prenom, String datenaissance, String telephone,
			String adresse, String nomphoto, byte[] photo) {
		super();
		this.username = username;
		this.password = password;
		this.active = active;
		this.nom = nom;
		this.prenom = prenom;
		this.datenaissance = datenaissance;
		this.telephone = telephone;
		this.adresse = adresse;
		this.nomphoto = nomphoto;
		this.photo = photo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "IDADMIN", unique = true, nullable = false)
	public Long getIdadmin() {
		return this.idadmin;
	}

	public void setIdadmin(Long idadmin) {
		this.idadmin = idadmin;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDROLE", nullable = false)
	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	@Column(name = "USERNAME")
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "PASSWORD")
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "ACTIVE")
	public Boolean getActive() {
		return this.active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	@Column(name = "NOM")
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "PRENOM")
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "DATENAISSANCE")
	public String getDatenaissance() {
		return this.datenaissance;
	}

	public void setDatenaissance(String datenaissance) {
		this.datenaissance = datenaissance;
	}

	@Column(name = "TELEPHONE")
	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	@Column(name = "ADRESSE")
	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	@Column(name = "NOMPHOTO")
	public String getNomphoto() {
		return this.nomphoto;
	}

	public void setNomphoto(String nomphoto) {
		this.nomphoto = nomphoto;
	}

	@Column(name = "PHOTO")
	public byte[] getPhoto() {
		return this.photo;
	}

	public void setPhoto(byte[] photo) {
		this.photo = photo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "administrateur")
	public Set<Ecole> getEcoles() {
		return this.ecoles;
	}

	public void setEcoles(Set<Ecole> ecoles) {
		this.ecoles = ecoles;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "administrateur")
	public Set<Gerant> getGerants() {
		return this.gerants;
	}

	public void setGerants(Set<Gerant> gerants) {
		this.gerants = gerants;
	}

	@Override
	public String toString() {
		return "Administrateur [idadmin=" + idadmin + ", username=" + username
				+ ", password=" + password + ", active=" + active + ", nom="
				+ nom + ", prenom=" + prenom + ", datenaissance="
				+ datenaissance + ", telephone=" + telephone + ", adresse="
				+ adresse + ", nomphoto=" + nomphoto + "]";
	}

}
