package com.projet.air2.entities;

// Generated 1 févr. 2017 02:18:12 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cours generated by hbm2java
 */
@Entity
@Table(name = "cours", catalog = "projetair")
public class Cours implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long idcours;
	private Ecole ecole;
	private String nomCours;
	private String resumeCours;
	private String dateCours;
	private Set<Enseigner> enseigners = new HashSet<Enseigner>(0);

	public Cours() {
	}

	public Cours(Ecole ecole) {
		this.ecole = ecole;
	}

	public Cours(Ecole ecole, String nomCours, String resumeCours,
			String dateCours, Set<Enseigner> enseigners) {
		this.ecole = ecole;
		this.nomCours = nomCours;
		this.resumeCours = resumeCours;
		this.dateCours = dateCours;
		this.enseigners = enseigners;
	}

	public Cours(String nomCours, String resumeCours, String dateCours) {
		super();
		this.nomCours = nomCours;
		this.resumeCours = resumeCours;
		this.dateCours = dateCours;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "IDCOURS", unique = true, nullable = false)
	public Long getIdcours() {
		return this.idcours;
	}

	public void setIdcours(Long idcours) {
		this.idcours = idcours;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDECOLE", nullable = false)
	public Ecole getEcole() {
		return this.ecole;
	}

	public void setEcole(Ecole ecole) {
		this.ecole = ecole;
	}

	@Column(name = "NOM_COURS")
	public String getNomCours() {
		return this.nomCours;
	}

	public void setNomCours(String nomCours) {
		this.nomCours = nomCours;
	}

	@Column(name = "RESUME_COURS", length = 65535)
	public String getResumeCours() {
		return this.resumeCours;
	}

	public void setResumeCours(String resumeCours) {
		this.resumeCours = resumeCours;
	}

	@Column(name = "DATE_COURS")
	public String getDateCours() {
		return this.dateCours;
	}

	public void setDateCours(String dateCours) {
		this.dateCours = dateCours;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cours")
	public Set<Enseigner> getEnseigners() {
		return this.enseigners;
	}

	public void setEnseigners(Set<Enseigner> enseigners) {
		this.enseigners = enseigners;
	}

	@Override
	public String toString() {
		return "Cours [idcours=" + idcours + ", nomCours=" + nomCours
				+ ", resumeCours=" + resumeCours + ", dateCours=" + dateCours
				+ "]";
	}

}
