package com.projet.air2.entities;

// Generated 1 févr. 2017 02:18:12 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ecole generated by hbm2java
 */
@Entity
@Table(name = "ecole", catalog = "projetair")
public class Ecole implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long idecole;
	private Administrateur administrateur;
	private Gerant gerant;
	private String designation;
	private String nomgerant;
	private String adresse;
	private String telephone;
	private String nomlogo;
	private byte[] logo;
	private Set<Gerant> gerants = new HashSet<Gerant>(0);
	private Set<Moniteur> moniteurs = new HashSet<Moniteur>(0);
	private Set<Cours> courses = new HashSet<Cours>(0);
	private Set<Permis> permises = new HashSet<Permis>(0);
	private Set<Eleve> eleves = new HashSet<Eleve>(0);

	public Ecole() {
	}

	public Ecole(Administrateur administrateur, Gerant gerant) {
		this.administrateur = administrateur;
		this.gerant = gerant;
	}

	public Ecole(Administrateur administrateur, Gerant gerant,
			String designation, String nomgerant, String adresse,
			String telephone, String nomlogo, byte[] logo, Set<Gerant> gerants,
			Set<Moniteur> moniteurs, Set<Cours> courses, Set<Permis> permises,
			Set<Eleve> eleves) {
		this.administrateur = administrateur;
		this.gerant = gerant;
		this.designation = designation;
		this.nomgerant = nomgerant;
		this.adresse = adresse;
		this.telephone = telephone;
		this.nomlogo = nomlogo;
		this.logo = logo;
		this.gerants = gerants;
		this.moniteurs = moniteurs;
		this.courses = courses;
		this.permises = permises;
		this.eleves = eleves;
	}

	public Ecole(String designation, String nomgerant, String adresse,
			String telephone, String nomlogo, byte[] logo) {
		super();
		this.designation = designation;
		this.nomgerant = nomgerant;
		this.adresse = adresse;
		this.telephone = telephone;
		this.nomlogo = nomlogo;
		this.logo = logo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "IDECOLE", unique = true, nullable = false)
	public Long getIdecole() {
		return this.idecole;
	}

	public void setIdecole(Long idecole) {
		this.idecole = idecole;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDADMIN", nullable = false)
	public Administrateur getAdministrateur() {
		return this.administrateur;
	}

	public void setAdministrateur(Administrateur administrateur) {
		this.administrateur = administrateur;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDGERANT", nullable = false)
	public Gerant getGerant() {
		return this.gerant;
	}

	public void setGerant(Gerant gerant) {
		this.gerant = gerant;
	}

	@Column(name = "DESIGNATION")
	public String getDesignation() {
		return this.designation;
	}

	public void setDesignation(String designation) {
		this.designation = designation;
	}

	@Column(name = "NOMGERANT")
	public String getNomgerant() {
		return this.nomgerant;
	}

	public void setNomgerant(String nomgerant) {
		this.nomgerant = nomgerant;
	}

	@Column(name = "ADRESSE")
	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	@Column(name = "TELEPHONE")
	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	@Column(name = "NOMLOGO")
	public String getNomlogo() {
		return this.nomlogo;
	}

	public void setNomlogo(String nomlogo) {
		this.nomlogo = nomlogo;
	}

	@Column(name = "LOGO")
	public byte[] getLogo() {
		return this.logo;
	}

	public void setLogo(byte[] logo) {
		this.logo = logo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ecole")
	public Set<Gerant> getGerants() {
		return this.gerants;
	}

	public void setGerants(Set<Gerant> gerants) {
		this.gerants = gerants;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ecole")
	public Set<Moniteur> getMoniteurs() {
		return this.moniteurs;
	}

	public void setMoniteurs(Set<Moniteur> moniteurs) {
		this.moniteurs = moniteurs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ecole")
	public Set<Cours> getCourses() {
		return this.courses;
	}

	public void setCourses(Set<Cours> courses) {
		this.courses = courses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ecole")
	public Set<Permis> getPermises() {
		return this.permises;
	}

	public void setPermises(Set<Permis> permises) {
		this.permises = permises;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ecole")
	public Set<Eleve> getEleves() {
		return this.eleves;
	}

	public void setEleves(Set<Eleve> eleves) {
		this.eleves = eleves;
	}

	@Override
	public String toString() {
		return "Ecole [idecole=" + idecole + ", designation=" + designation
				+ ", nomgerant=" + nomgerant + ", adresse=" + adresse
				+ ", telephone=" + telephone + ", nomlogo=" + nomlogo + "]";
	}

	 

}
