package com.projet.air2.entities;

// Generated 1 févr. 2017 02:18:12 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Eleve generated by hbm2java
 */
@Entity
@Table(name = "eleve", catalog = "projetair")
public class Eleve implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long ideleve;
	private Permis permis;
	private Role role;
	private Ecole ecole;
	private Gerant gerant;
	private String username;
	private String password;
	private Boolean active;
	private String nom;
	private String prenom;
	private String datenaissance;
	private String telephone;
	private String adresse;
	private String nomphoto;
	private byte[] photo;
	private String dateinscription;
	private Set<Enseigner> enseigners = new HashSet<Enseigner>(0);

	public Eleve() {
	}

	public Eleve(Permis permis, Role role, Ecole ecole, Gerant gerant) {
		this.permis = permis;
		this.role = role;
		this.ecole = ecole;
		this.gerant = gerant;
	}

	public Eleve(Permis permis, Role role, Ecole ecole, Gerant gerant,
			String username, String password, Boolean active, String nom,
			String prenom, String datenaissance, String telephone,
			String adresse, String nomphoto, byte[] photo,
			String dateinscription, Set<Enseigner> enseigners) {
		this.permis = permis;
		this.role = role;
		this.ecole = ecole;
		this.gerant = gerant;
		this.username = username;
		this.password = password;
		this.active = active;
		this.nom = nom;
		this.prenom = prenom;
		this.datenaissance = datenaissance;
		this.telephone = telephone;
		this.adresse = adresse;
		this.nomphoto = nomphoto;
		this.photo = photo;
		this.dateinscription = dateinscription;
		this.enseigners = enseigners;
	}

	public Eleve(String username, String password, Boolean active, String nom,
			String prenom, String datenaissance, String telephone,
			String adresse, String nomphoto) {
		super();
		this.username = username;
		this.password = password;
		this.active = active;
		this.nom = nom;
		this.prenom = prenom;
		this.datenaissance = datenaissance;
		this.telephone = telephone;
		this.adresse = adresse;
		this.nomphoto = nomphoto;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "IDELEVE", unique = true, nullable = false)
	public Long getIdeleve() {
		return this.ideleve;
	}

	public void setIdeleve(Long ideleve) {
		this.ideleve = ideleve;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDPERMIS", nullable = false)
	public Permis getPermis() {
		return this.permis;
	}

	public void setPermis(Permis permis) {
		this.permis = permis;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDROLE", nullable = false)
	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDECOLE", nullable = false)
	public Ecole getEcole() {
		return this.ecole;
	}

	public void setEcole(Ecole ecole) {
		this.ecole = ecole;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDGERANT", nullable = false)
	public Gerant getGerant() {
		return this.gerant;
	}

	public void setGerant(Gerant gerant) {
		this.gerant = gerant;
	}

	@Column(name = "USERNAME")
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "PASSWORD")
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "ACTIVE")
	public Boolean getActive() {
		return this.active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	@Column(name = "NOM")
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "PRENOM")
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "DATENAISSANCE")
	public String getDatenaissance() {
		return this.datenaissance;
	}

	public void setDatenaissance(String datenaissance) {
		this.datenaissance = datenaissance;
	}

	@Column(name = "TELEPHONE")
	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	@Column(name = "ADRESSE")
	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	@Column(name = "NOMPHOTO")
	public String getNomphoto() {
		return this.nomphoto;
	}

	public void setNomphoto(String nomphoto) {
		this.nomphoto = nomphoto;
	}

	@Column(name = "PHOTO")
	public byte[] getPhoto() {
		return this.photo;
	}

	public void setPhoto(byte[] photo) {
		this.photo = photo;
	}

	@Column(name = "DATEINSCRIPTION")
	public String getDateinscription() {
		return this.dateinscription;
	}

	public void setDateinscription(String dateinscription) {
		this.dateinscription = dateinscription;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "eleve")
	public Set<Enseigner> getEnseigners() {
		return this.enseigners;
	}

	public void setEnseigners(Set<Enseigner> enseigners) {
		this.enseigners = enseigners;
	}

}
