package com.projet.air2.entities;

// Generated 1 févr. 2017 02:18:12 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EnseignerId generated by hbm2java
 */
@Embeddable
public class EnseignerId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long idmoniteur;
	private long ideleve;
	private long idcours;

	public EnseignerId() {
	}

	public EnseignerId(long idmoniteur, long ideleve, long idcours) {
		this.idmoniteur = idmoniteur;
		this.ideleve = ideleve;
		this.idcours = idcours;
	}

	@Column(name = "IDMONITEUR", nullable = false)
	public long getIdmoniteur() {
		return this.idmoniteur;
	}

	public void setIdmoniteur(long idmoniteur) {
		this.idmoniteur = idmoniteur;
	}

	@Column(name = "IDELEVE", nullable = false)
	public long getIdeleve() {
		return this.ideleve;
	}

	public void setIdeleve(long ideleve) {
		this.ideleve = ideleve;
	}

	@Column(name = "IDCOURS", nullable = false)
	public long getIdcours() {
		return this.idcours;
	}

	public void setIdcours(long idcours) {
		this.idcours = idcours;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EnseignerId))
			return false;
		EnseignerId castOther = (EnseignerId) other;

		return (this.getIdmoniteur() == castOther.getIdmoniteur())
				&& (this.getIdeleve() == castOther.getIdeleve())
				&& (this.getIdcours() == castOther.getIdcours());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getIdmoniteur();
		result = 37 * result + (int) this.getIdeleve();
		result = 37 * result + (int) this.getIdcours();
		return result;
	}

}
