package com.projet.air2.entities;

// Generated 1 févr. 2017 02:18:12 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Gerant generated by hbm2java
 */
@Entity
@Table(name = "gerant", catalog = "projetair")
public class Gerant implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long idgerant;
	private Administrateur administrateur;
	private Role role;
	private Ecole ecole;
	private String username;
	private String password;
	private Boolean active;
	private String nom;
	private String prenom;
	private String datenaissance;
	private String telephone;
	private String adresse;
	private String nomphoto;
	private byte[] photo;
	private Set<Moniteur> moniteurs = new HashSet<Moniteur>(0);
	private Set<Eleve> eleves = new HashSet<Eleve>(0);
	private Set<Ecole> ecoles = new HashSet<Ecole>(0);

	public Gerant() {
	}

	public Gerant(Administrateur administrateur, Role role) {
		this.administrateur = administrateur;
		this.role = role;
	}

	public Gerant(Administrateur administrateur, Role role, Ecole ecole,
			String username, String password, Boolean active, String nom,
			String prenom, String datenaissance, String telephone,
			String adresse, String nomphoto, byte[] photo,
			Set<Moniteur> moniteurs, Set<Eleve> eleves, Set<Ecole> ecoles) {
		this.administrateur = administrateur;
		this.role = role;
		this.ecole = ecole;
		this.username = username;
		this.password = password;
		this.active = active;
		this.nom = nom;
		this.prenom = prenom;
		this.datenaissance = datenaissance;
		this.telephone = telephone;
		this.adresse = adresse;
		this.nomphoto = nomphoto;
		this.photo = photo;
		this.moniteurs = moniteurs;
		this.eleves = eleves;
		this.ecoles = ecoles;
	}

	public Gerant(String username, String password, Boolean active, String nom,
			String prenom, String datenaissance, String telephone,
			String adresse, String nomphoto, byte[] photo) {
		super();
		this.username = username;
		this.password = password;
		this.active = active;
		this.nom = nom;
		this.prenom = prenom;
		this.datenaissance = datenaissance;
		this.telephone = telephone;
		this.adresse = adresse;
		this.nomphoto = nomphoto;
		this.photo = photo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "IDGERANT", unique = true, nullable = false)
	public Long getIdgerant() {
		return this.idgerant;
	}

	public void setIdgerant(Long idgerant) {
		this.idgerant = idgerant;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDADMIN", nullable = false)
	public Administrateur getAdministrateur() {
		return this.administrateur;
	}

	public void setAdministrateur(Administrateur administrateur) {
		this.administrateur = administrateur;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDROLE", nullable = false)
	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDECOLE")
	public Ecole getEcole() {
		return this.ecole;
	}

	public void setEcole(Ecole ecole) {
		this.ecole = ecole;
	}

	@Column(name = "USERNAME")
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "PASSWORD")
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "ACTIVE")
	public Boolean getActive() {
		return this.active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	@Column(name = "NOM")
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "PRENOM")
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "DATENAISSANCE")
	public String getDatenaissance() {
		return this.datenaissance;
	}

	public void setDatenaissance(String datenaissance) {
		this.datenaissance = datenaissance;
	}

	@Column(name = "TELEPHONE")
	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	@Column(name = "ADRESSE")
	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	@Column(name = "NOMPHOTO")
	public String getNomphoto() {
		return this.nomphoto;
	}

	public void setNomphoto(String nomphoto) {
		this.nomphoto = nomphoto;
	}

	@Column(name = "PHOTO")
	public byte[] getPhoto() {
		return this.photo;
	}

	public void setPhoto(byte[] photo) {
		this.photo = photo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "gerant")
	public Set<Moniteur> getMoniteurs() {
		return this.moniteurs;
	}

	public void setMoniteurs(Set<Moniteur> moniteurs) {
		this.moniteurs = moniteurs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "gerant")
	public Set<Eleve> getEleves() {
		return this.eleves;
	}

	public void setEleves(Set<Eleve> eleves) {
		this.eleves = eleves;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "gerant")
	public Set<Ecole> getEcoles() {
		return this.ecoles;
	}

	public void setEcoles(Set<Ecole> ecoles) {
		this.ecoles = ecoles;
	}

	@Override
	public String toString() {
		return "Gerant [idgerant=" + idgerant + ", username=" + username
				+ ", password=" + password + ", active=" + active + ", nom="
				+ nom + ", prenom=" + prenom + ", datenaissance="
				+ datenaissance + ", telephone=" + telephone + ", adresse="
				+ adresse + ", nomphoto=" + nomphoto + "]";
	}

}
