package com.projet.air2.entities;

// Generated 1 févr. 2017 02:18:12 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Permis generated by hbm2java
 */
@Entity
@Table(name = "permis", catalog = "projetair")
public class Permis implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long idpermis;
	private Ecole ecole;
	private String nomPermis;
	private Float prixPermis;
	private Set<Eleve> eleves = new HashSet<Eleve>(0);

	public Permis() {
	}

	public Permis(Ecole ecole) {
		this.ecole = ecole;
	}

	public Permis(Ecole ecole, String nomPermis, Float prixPermis,
			Set<Eleve> eleves) {
		this.ecole = ecole;
		this.nomPermis = nomPermis;
		this.prixPermis = prixPermis;
		this.eleves = eleves;
	}

	public Permis(String nomPermis, Float prixPermis) {
		super();
		this.nomPermis = nomPermis;
		this.prixPermis = prixPermis;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "IDPERMIS", unique = true, nullable = false)
	public Long getIdpermis() {
		return this.idpermis;
	}

	public void setIdpermis(Long idpermis) {
		this.idpermis = idpermis;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDECOLE", nullable = false)
	public Ecole getEcole() {
		return this.ecole;
	}

	public void setEcole(Ecole ecole) {
		this.ecole = ecole;
	}

	@Column(name = "NOM_PERMIS")
	public String getNomPermis() {
		return this.nomPermis;
	}

	public void setNomPermis(String nomPermis) {
		this.nomPermis = nomPermis;
	}

	@Column(name = "PRIX_PERMIS", precision = 12, scale = 0)
	public Float getPrixPermis() {
		return this.prixPermis;
	}

	public void setPrixPermis(Float prixPermis) {
		this.prixPermis = prixPermis;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "permis")
	public Set<Eleve> getEleves() {
		return this.eleves;
	}

	public void setEleves(Set<Eleve> eleves) {
		this.eleves = eleves;
	}

	@Override
	public String toString() {
		return "Permis [idpermis=" + idpermis + ", nomPermis=" + nomPermis
				+ ", prixPermis=" + prixPermis + "]";
	}

}
