package com.projet.air2.entities;

// Generated 1 févr. 2017 02:18:12 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name = "role", catalog = "projetair")
public class Role implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long idrole;
	private String rolename;
	private Set<Eleve> eleves = new HashSet<Eleve>(0);
	private Set<Administrateur> administrateurs = new HashSet<Administrateur>(0);
	private Set<Moniteur> moniteurs = new HashSet<Moniteur>(0);
	private Set<Gerant> gerants = new HashSet<Gerant>(0);

	public Role() {
	}

	public Role(String rolename, Set<Eleve> eleves,
			Set<Administrateur> administrateurs, Set<Moniteur> moniteurs,
			Set<Gerant> gerants) {
		this.rolename = rolename;
		this.eleves = eleves;
		this.administrateurs = administrateurs;
		this.moniteurs = moniteurs;
		this.gerants = gerants;
	}

	public Role(String rolename) {
		super();
		this.rolename = rolename;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "IDROLE", unique = true, nullable = false)
	public Long getIdrole() {
		return this.idrole;
	}

	public void setIdrole(Long idrole) {
		this.idrole = idrole;
	}

	@Column(name = "ROLENAME")
	public String getRolename() {
		return this.rolename;
	}

	public void setRolename(String rolename) {
		this.rolename = rolename;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "role")
	public Set<Eleve> getEleves() {
		return this.eleves;
	}

	public void setEleves(Set<Eleve> eleves) {
		this.eleves = eleves;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "role")
	public Set<Administrateur> getAdministrateurs() {
		return this.administrateurs;
	}

	public void setAdministrateurs(Set<Administrateur> administrateurs) {
		this.administrateurs = administrateurs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "role")
	public Set<Moniteur> getMoniteurs() {
		return this.moniteurs;
	}

	public void setMoniteurs(Set<Moniteur> moniteurs) {
		this.moniteurs = moniteurs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "role")
	public Set<Gerant> getGerants() {
		return this.gerants;
	}

	public void setGerants(Set<Gerant> gerants) {
		this.gerants = gerants;
	}

	@Override
	public String toString() {
		return "Role [idrole=" + idrole + ", rolename=" + rolename + "]";
	}

}
